### ISSUE TITLE
How do I compile the RAT and where do I specify the CNC URL?

### ISSUE THREAD

**Issue by slezercc** [ElliotAlderson51/Fsociety-RAT#1]
edit: this project is not very well documented, and is lacking a php file to create the needed tables and rows in the database. The login also doesnt work.

**Comment by violentqm** [comment]
sad this is a really persistent rat with features im still looking for in any other a root kit process hollowing ect anyone has and recommendations for any other rat with the same features?

**Comment by ElliotAlderson51** [comment]
Apologies for the delay in addressing your project concerns. As an active member of the army, I have limited availability to respond. Rest assured, I will fix all the problems once I have more time. Thank you for your understanding.

**Comment by ElliotAlderson51** [comment]
> sad this is a really persistent rat with features im still looking for in any other a root kit process hollowing ect anyone has and recommendations for any other rat with the same features?

Apologies for the delay in addressing your project concerns. As an active member of the army, I have limited availability to respond. Rest assured, I will fix all the problems once I have more time. Thank you for your understanding.

**Comment by ghost** [comment]
Great features you have here Elliot, its awesome to look at. To the people who needs documentation to get this to work should never use it in the first place. I would suggest fixing the databases or writing your own RAT to those who complain. There are many great articles and books.

I'm having thoughts on collaborating with you Elliot, I'm currently a Go Lang/Python person working on a C2 based on commercial third party workplace apps. Let me know if the project is open to contributions, I will write some functionalities and improve the documentation further in my free time.

- The towers of control grow taller each day. Climb them while you can. The fall is inevitable.  Until next time, friend.

**Comment by ElliotAlderson51** [comment]
> Great features you have here Elliot, its awesome to look at. To the people who needs documentation to get this to work should never use it in the first place. I would suggest fixing the databases or writing your own RAT to those who complain. There are many great articles and books.
> 
> 
> 
> I'm having thoughts on collaborating with you Elliot, I'm currently a Go Lang/Python person working on a C2 based on commercial third party workplace apps. Let me know if the project is open to contributions, I will write some functionalities and improve the documentation further in my free time.
> 
> 
> 
> - The towers of control grow taller each day. Climb them while you can. The fall is inevitable.  Until next time, friend.

Hey there! I'm happy to hear that you liked it! As someone in the military, I currently don't have access to a laptop or PC for fixing and improving the project. However, soon I'll have more time to dedicate to these tasks. Thanks.

**Comment by violentqm** [comment]
> > Great features you have here Elliot, its awesome to look at. To the people who needs documentation to get this to work should never use it in the first place. I would suggest fixing the databases or writing your own RAT to those who complain. There are many great articles and books.
> > I'm having thoughts on collaborating with you Elliot, I'm currently a Go Lang/Python person working on a C2 based on commercial third party workplace apps. Let me know if the project is open to contributions, I will write some functionalities and improve the documentation further in my free time.
> > 
> > * The towers of control grow taller each day. Climb them while you can. The fall is inevitable.  Until next time, friend.
> 
> Hey there! I'm happy to hear that you liked it! As someone in the military, I currently don't have access to a laptop or PC for fixing and improving the project. However, soon I'll have more time to dedicate to these tasks. Thanks.

wow dude i hope you are fine hope you will be fine and back soon military is hard
